---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/register":
    post:
      summary: create user
      tags:
      - Register User
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                    message: Usuário registrado com sucesso
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: email@email.com
                password:
                  type: string
                  default: '1234567890'
                password_confirmation:
                  type: string
                  default: '1234567890'
              required:
              - email
              - password
              - password_confirmation
  "/login":
    post:
      summary: login
      tags:
      - Authentication User
      parameters:
      - name: email
        in: query
        description: Email
        value: email@email.com
        schema:
          type: string
      - name: password
        in: query
        description: Password
        value: '1234567890'
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyfQ.cur2kIbFqR8WAnjVG9uuFrs-kEmllisZ-tRU-h8DD0w
  "/users/{id}/update_password":
    put:
      summary: update password
      tags:
      - Change Password
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        value: '1'
        schema:
          type: string
      - name: password
        in: query
        description: New Password
        required: true
        schema:
          type: string
      - name: password_confirmation
        in: query
        description: New Password Confirmation
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                    message: Senha atualizada com sucesso
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Your Bearer token
servers:
- url: http://localhost:3000
  description: Local server
